// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, channel, core, h, helpers, motherShip, protocol, protocolHost, server, startTime, subscriptionMan, v, validator, _,
    __slice = [].slice;

  _ = require('underscore');

  Backbone = require('backbone4000');

  h = helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  startTime = new Date().getTime();

  core = exports.core = subscriptionMan.fancy.extend4000({
    log: function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.verbose) {
        console.log(args);
      }
      if (this.logger) {
        return this.logger.log.apply(this.logger, args);
      }
    },
    initialize: function() {
      if (this.get('verbose')) {
        this.verobse = true;
      }
      return this.when('parent', (function(_this) {
        return function(parent) {
          _this.parent = parent;
          if (_this.parent.verbose) {
            _this.verbose = true;
          }
          if (_this.parent.logger) {
            return _this.set({
              logger: _this.parent.logger.child()
            });
          }
        };
      })(this));
    },
    name: function() {
      if (this.parent) {
        return this.parent.name() + "-" + this.get('name');
      } else {
        return this.get('name') || 'noname';
      }
    },
    end: function() {
      if (this.ended) {
        return;
      } else {
        this.ended = true;
      }
      this.log('ending');
      return this.trigger('end');
    }
  });

  protocolHost = exports.protocolHost = core.extend4000({
    initialize: function(options) {
      if (options == null) {
        options = {};
      }
      this.when('parent', (function(_this) {
        return function(parent) {
          if (parent.logger) {
            return _this.set({
              logger: parent.logger.child()
            });
          }
        };
      })(this));
      this.when('logger', (function(_this) {
        return function(logger) {
          var oldName;
          _this.logger = logger;
          logger.addTags(oldName = _this.get('name') || "unnamed");
          return _this.on('change:name', function(self, name) {
            logger.delTags(oldName);
            return logger.addTags(oldName = name);
          });
        };
      })(this));
      return this.protocols = {};
    },
    hasProtocol: function(protocol) {
      if (typeof protocol === 'function') {
        return Boolean(this[protocol.prototype.defaults.name]);
      }
      if (typeof protocol === 'object') {
        return Boolean(this[protocol.name()]);
      }
      throw "what is this?";
    },
    addProtocol: function(protocol) {
      var name;
      if (!(name = protocol.name())) {
        throw "what is this?";
      }
      if (this.hasProtocol(protocol)) {
        return;
      }
      _.map(protocol.requires, (function(_this) {
        return function(dependancyProtocol) {
          if (!_this.hasProtocol(dependancyProtocol)) {
            return _this.addProtocol(new dependancyProtocol());
          }
        };
      })(this));
      this[name] = protocol;
      protocol.set({
        parent: this
      });
      if (protocol.functions) {
        return _.extend(this, protocol.functions());
      }
    }
  });

  channel = exports.channel = protocolHost.extend4000({
    initialize: function() {
      return this.realm = this.getRealm();
    },
    send: function(msg) {
      throw 'not implemented';
    },
    getRealm: function() {
      return {
        client: this
      };
    }
  });

  protocol = exports.protocol = core.extend4000({
    requires: []
  });

  server = exports.server = protocolHost.extend4000({
    initialize: function() {
      var channelClass;
      this.clients = this.children = {};
      if (channelClass = this.get('channelClass') || this.channelClass) {
        return this.channelClass = this.defaultChannelClass.extend4000(channelClass);
      } else {
        return this.channelClass = this.defaultChannelClass;
      }
    }
  });

  motherShip = exports.motherShip = function(name) {
    var model;
    model = {};
    model.initialize = function() {
      return this[name + "s"] = {};
    };
    model[name] = function(instanceName, attributes) {
      var instance, instanceClass;
      if (attributes == null) {
        attributes = {};
      }
      if (instance = this[name + "s"][instanceName]) {
        return instance;
      }
      instanceClass = this.get(name + "Class");
      if (!instanceClass) {
        throw "I don't have " + name + "Class defined";
      }
      instance = this[name + "s"][instanceName] = new instanceClass(_.extend({
        parent: this,
        name: instanceName
      }, attributes));
      instance.once('end', (function(_this) {
        return function() {
          return delete _this[name + "s"][instanceName];
        };
      })(this));
      this.trigger('new' + helpers.capitalize(name), instance);
      return instance;
    };
    return Backbone.Model.extend4000(model);
  };

}).call(this);
