// Generated by LiveScript 1.3.1
(function(){
  var validator, v, Server, Client, helpers, express, Http, port, colors, gimmeEnv;
  validator = require('validator2-extras');
  v = validator.v;
  Server = require('./transports/server/websocket');
  Client = require('./transports/client/websocket');
  helpers = require('helpers');
  express = require('express');
  Http = require('http');
  port = 8192;
  colors = require('colors');
  gimmeEnv = function(callback){
    var app, http, lwebs, lwebc;
    app = express();
    http = Http.createServer(app);
    http.listen(port);
    lwebs = new Server.webSocketServer({
      http: http,
      verbose: false
    });
    lwebc = new Client.webSocketClient({
      host: 'http://localhost:' + port,
      verbose: false
    });
    return lwebs.on('connect', function(s){
      return callback(lwebs, s, lwebc);
    });
  };
  gimmeEnv(function(lweb, server, client){});
}).call(this);
