// Generated by CoffeeScript 1.9.3
(function() {
  var Backbone, Nssocket, _, helpers, nssocketClient, subscriptionMan, v, validator;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  Nssocket = require('nssocket');

  _.extend(exports, require('../nssocket'));

  nssocketClient = exports.nssocketClient = exports.nssocketChannel.extend4000({
    defaults: {
      name: 'nssocketClient',
      reconnect: false
    },
    initialize: function() {
      return this.connect();
    },
    connect: function() {
      var nssocket;
      if (this.nssocket) {
        this.nssocket.destroy();
      }
      this.set({
        nssocket: nssocket = Nssocket.NsSocket({
          reconnect: this.get('reconnect'),
          type: 'tcp4'
        })
      });
      nssocket.connect(this.get('host'), this.get('port'));
      return this.trigger('connect');
    }
  });

}).call(this);
