// Generated by CoffeeScript 1.9.3
(function() {
  var Backbone, _, core, engineIoChannel, helpers, subscriptionMan, util, v, validator;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  util = require('util');

  core = require('../core');

  engineIoChannel = exports.engineIoChannel = core.channel.extend4000({
    defaults: {
      name: 'engineIo'
    },
    ip: function() {
      var ip, request;
      request = this.engineIo.request;
      ip = request.headers['x-real-ip'] || request.headers['x-forwarded-for'] || request.connection.remoteAddress;
      return _.last(ip.split(":"));
    },
    initialize: function() {
      this.engineIo = this.get('engineIo');
      this.set({
        name: 'ip-' + this.ip()
      });
      this.engineIo.on('message', (function(_this) {
        return function(msg) {
          msg = JSON.parse(msg);
          _this.log('< ' + util.inspect(msg, {
            depth: 0
          }), msg, 'in');
          _this.event(msg, _this.realm);
          return _this.trigger('msg', msg);
        };
      })(this));
      this.engineIo.once('close', (function(_this) {
        return function() {
          _this.trigger('disconnect');
          _this.log("Lost Connection");
          return _this.end();
        };
      })(this));
      return this.when('parent', (function(_this) {
        return function(parent) {
          parent.on('end', function() {
            return _this.end();
          });
          return _this.on('msg', function(msg) {
            return parent.event(msg, _this.realm);
          });
        };
      })(this));
    },
    send: function(msg) {
      this.log("> " + util.inspect(msg, {
        depth: 0
      }), msg, "out");
      return this.engineIo.send(JSON.stringify(msg));
    }
  });

}).call(this);
