// Generated by CoffeeScript 1.9.3
(function() {
  var Backbone, _, core, engineIoChannel, helpers, subscriptionMan, util, v, validator;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  util = require('util');

  core = require('../core');

  engineIoChannel = exports.engineIoChannel = core.channel.extend4000({
    defaults: {
      name: 'engineIo'
    },
    initialize: function() {
      this.when('engineIo', (function(_this) {
        return function(engineIo) {
          var disconnectListener;
          _this.engineIo = engineIo;
          _this.listenTo(_this.engineIo, 'message', function(msg) {
            msg = JSON.parse(msg);
            _this.log('< ' + JSON.stringify(msg), msg, 'in');
            _this.event(msg, _this.realm);
            return _this.trigger('msg', msg);
          });
          disconnectListener = function() {
            _this.engineIo.removeListener('error', disconnectListener);
            _this.engineIo.removeListener('close', disconnectListener);
            _this.trigger('disconnect');
            _this.log("Lost Connection", {}, "disconnect");
            return _this.end();
          };
          _this.engineIo.once('error', disconnectListener);
          return _this.engineIo.once('close', disconnectListener);
        };
      })(this));
      return this.when('parent', (function(_this) {
        return function(parent) {
          parent.on('end', function() {
            return _this.end();
          });
          return _this.on('msg', function(msg) {
            return parent.event(msg, _this.realm);
          });
        };
      })(this));
    },
    end: function() {
      if (typeof this.engineIo === "function") {
        this.engineIo(typeof transport === "function" ? transport(typeof pollXhr === "function" ? pollXhr(abort()) : void 0) : void 0);
      }
      if (typeof this.engineIo === "function") {
        this.engineIo(typeof transport === "function" ? transport(typeof sendXhr === "function" ? sendXhr(abort()) : void 0) : void 0);
      }
      return core.channel.prototype.end.call(this);
    },
    send: function(msg) {
      return this.engineIo.send(JSON.stringify(msg));
    }
  });

}).call(this);
